"""init mysql

Revision ID: 7bac4bf8eb60
Revises: 
Create Date: 2026-01-20 11:49:20.525202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bac4bf8eb60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url_imagen', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('zonas_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cp_inicio', sa.Integer(), nullable=False),
    sa.Column('cp_fin', sa.Integer(), nullable=False),
    sa.Column('tipo_envio', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=150), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('extra', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('costo_envio', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('stock_state', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=255), nullable=True),
    sa.Column('descripcion_larga', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('url_imagen_principal', sa.String(length=200), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('vistas', sa.Integer(), nullable=True),
    sa.Column('valoracion_promedio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('id_preferencia', sa.String(length=100), nullable=True),
    sa.Column('url_checkout', sa.String(length=300), nullable=True),
    sa.Column('referencia_externa', sa.String(length=100), nullable=True),
    sa.Column('id_pago_mp', sa.String(length=100), nullable=True),
    sa.Column('id_orden_mercante', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('detalle_estado', sa.String(length=100), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('tipo_pago', sa.String(length=50), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('notificado_user', sa.Boolean(), nullable=True),
    sa.Column('notificado_admin', sa.Boolean(), nullable=True),
    sa.Column('ultimo_estado_notificado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pago_mp'),
    sa.UniqueConstraint('id_preferencia')
    )
    op.create_table('pedido_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resenas')
    op.drop_table('pedido_detalle')
    op.drop_table('pagos')
    op.drop_table('imagenes_productos')
    op.drop_table('favoritos')
    op.drop_table('productos')
    op.drop_table('pedidos')
    op.drop_table('direcciones')
    op.drop_table('zonas_envio')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
