"""Agrego cascade delete a PedidoDetalle

Revision ID: 83ce28c55cca
Revises: 
Create Date: 2025-10-15 17:39:21.135659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '83ce28c55cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direcciones', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('calle',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('provincia',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('codigo_postal',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('especificaciones')
        batch_op.drop_column('marca')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('especificaciones', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('direcciones', schema=None) as batch_op:
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('codigo_postal',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('provincia',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('calle',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
